/*
 Generated by typeshare 1.13.4
*/

export interface AuthConfig {
	session_timeout_secs: number;
	single_user_allow_multiple_sessions: boolean;
}

export interface VideoConfig {
	device?: string;
	format?: string;
	width: number;
	height: number;
	fps: number;
	quality: number;
}

export enum HidBackend {
	Otg = "otg",
	Ch9329 = "ch9329",
	None = "none",
}

export interface OtgDescriptorConfig {
	vendor_id: number;
	product_id: number;
	manufacturer: string;
	product: string;
	serial_number?: string;
}

export enum OtgHidProfile {
	Full = "full",
	FullNoConsumer = "full_no_consumer",
	LegacyKeyboard = "legacy_keyboard",
	LegacyMouseRelative = "legacy_mouse_relative",
	Custom = "custom",
}

export interface OtgHidFunctions {
	keyboard: boolean;
	mouse_relative: boolean;
	mouse_absolute: boolean;
	consumer: boolean;
}

export interface Ch9329DescriptorConfig {
	vendor_id: number;
	product_id: number;
	manufacturer: string;
	product: string;
	serial_number?: string;
}

export interface HidConfig {
	backend: HidBackend;
	otg_udc?: string;
	otg_descriptor?: OtgDescriptorConfig;
	otg_profile?: OtgHidProfile;
	otg_functions?: OtgHidFunctions;
	otg_keyboard_leds?: boolean;
	ch9329_port: string;
	ch9329_baudrate: number;
	ch9329_hybrid_mouse?: boolean;
	ch9329_descriptor?: Ch9329DescriptorConfig;
	mouse_absolute: boolean;
}

export enum OtgNetworkDriverMode {
	Ncm = "ncm",
	Ecm = "ecm",
	Rndis = "rndis",
}

export interface OtgNetworkConfig {
	enabled: boolean;
	driver_mode: OtgNetworkDriverMode;
	/** Empty means select the connected NetworkManager Ethernet interface. */
	bridge_interface: string;
	/** Empty values are resolved from the machine identity at runtime. */
	host_mac: string;
	device_mac: string;
}

export interface MsdConfig {
	enabled: boolean;
	msd_dir: string;
}

export enum AtxDriverType {
	Gpio = "gpio",
	UsbRelay = "usbrelay",
	Serial = "serial",
	None = "none",
}

export enum ActiveLevel {
	High = "high",
	Low = "low",
}

export interface AtxOutputBinding {
	enabled: boolean;
	device: string;
	pin: number;
	active_level: ActiveLevel;
}

export interface AtxInputBinding {
	enabled: boolean;
	device: string;
	pin: number;
	active_level: ActiveLevel;
}

export interface AtxConfig {
	enabled: boolean;
	driver: AtxDriverType;
	device: string;
	baud_rate: number;
	power: AtxOutputBinding;
	reset: AtxOutputBinding;
	led: AtxInputBinding;
	hdd: AtxInputBinding;
	wol_interface: string;
}

export interface AudioConfig {
	enabled: boolean;
	device: string;
	quality: string;
}

export enum StreamMode {
	WebRTC = "webrtc",
	Mjpeg = "mjpeg",
}

export enum EncoderType {
	Auto = "auto",
	Software = "software",
	Vaapi = "vaapi",
	Nvenc = "nvenc",
	Qsv = "qsv",
	Amf = "amf",
	Rkmpp = "rkmpp",
	V4l2m2m = "v4l2m2m",
}

export type BitratePreset = 
	| { type: "Speed", value?: undefined }
	| { type: "Balanced", value?: undefined }
	| { type: "Quality", value?: undefined }
	| { type: "Custom", value: number };

export interface StreamConfig {
	mode: StreamMode;
	encoder: EncoderType;
	bitrate_preset: BitratePreset;
	stun_server?: string;
	turn_server?: string;
	turn_username?: string;
	turn_password?: string;
}

export interface WebConfig {
	http_port: number;
	https_port: number;
	bind_addresses: string[];
	bind_address: string;
	https_enabled: boolean;
	ssl_cert_path?: string;
	ssl_key_path?: string;
}

export interface ComputerUseConfig {
	enabled: boolean;
	base_url: string;
	model: string;
}

export interface TtydConfig {
	enabled: boolean;
	shell: string;
}

export interface GostcConfig {
	enabled: boolean;
	addr: string;
	key: string;
	tls: boolean;
}

export interface EasytierConfig {
	enabled: boolean;
	network_name: string;
	network_secret: string;
	peer_urls: string[];
	virtual_ip?: string;
}

export enum FrpcConfigMode {
	Quick = "quick",
	Full = "full",
}

export enum FrpProxyType {
	Tcp = "tcp",
	Udp = "udp",
	Http = "http",
	Https = "https",
	Stcp = "stcp",
	Sudp = "sudp",
	Xtcp = "xtcp",
}

export interface FrpcConfig {
	enabled: boolean;
	config_mode: FrpcConfigMode;
	proxy_name: string;
	proxy_type: FrpProxyType;
	server_addr: string;
	server_port: number;
	token: string;
	local_ip: string;
	local_port: number;
	remote_port?: number;
	custom_domain?: string;
	secret_key: string;
	tls: boolean;
	custom_toml: string;
}

export interface ExtensionsConfig {
	ttyd: TtydConfig;
	gostc: GostcConfig;
	easytier: EasytierConfig;
	frpc: FrpcConfig;
}

export enum RustDeskCodec {
	H264 = "h264",
	H265 = "h265",
}

export interface RustDeskConfig {
	enabled: boolean;
	codec: RustDeskCodec;
	rendezvous_server: string;
	relay_server?: string;
	device_id: string;
}

export enum VncEncoding {
	TightJpeg = "tight_jpeg",
	H264 = "h264",
}

export interface VncConfig {
	enabled: boolean;
	bind: string;
	port: number;
	encoding: VncEncoding;
	allow_one_client: boolean;
}

export enum RtspCodec {
	H264 = "h264",
	H265 = "h265",
}

export interface RtspConfig {
	enabled: boolean;
	bind: string;
	port: number;
	path: string;
	allow_one_client: boolean;
	codec: RtspCodec;
	username?: string;
}

export interface RedfishConfig {
	enabled: boolean;
}

export interface WatchdogConfig {
	enabled: boolean;
}

export interface AppConfig {
	initialized: boolean;
	auth: AuthConfig;
	video: VideoConfig;
	hid: HidConfig;
	otg_network: OtgNetworkConfig;
	msd: MsdConfig;
	atx: AtxConfig;
	audio: AudioConfig;
	stream: StreamConfig;
	web: WebConfig;
	computer_use: ComputerUseConfig;
	extensions: ExtensionsConfig;
	rustdesk: RustDeskConfig;
	vnc: VncConfig;
	rtsp: RtspConfig;
	redfish: RedfishConfig;
	watchdog: WatchdogConfig;
}

/** Update for a single ATX output binding */
export interface AtxOutputBindingUpdate {
	enabled?: boolean;
	device?: string;
	pin?: number;
	active_level?: ActiveLevel;
}

/** Update for ATX GPIO input sensing */
export interface AtxInputBindingUpdate {
	enabled?: boolean;
	device?: string;
	pin?: number;
	active_level?: ActiveLevel;
}

/** ATX configuration update request */
export interface AtxConfigUpdate {
	enabled?: boolean;
	driver?: AtxDriverType;
	device?: string;
	baud_rate?: number;
	/** Power button configuration */
	power?: AtxOutputBindingUpdate;
	/** Reset button configuration */
	reset?: AtxOutputBindingUpdate;
	/** LED sensing configuration */
	led?: AtxInputBindingUpdate;
	/** HDD activity sensing configuration */
	hdd?: AtxInputBindingUpdate;
	/** Network interface for WOL packets (empty = auto) */
	wol_interface?: string;
}

export interface AtxDevices {
	gpio_chips: string[];
	usb_relays: string[];
	serial_ports: string[];
}

export interface AudioConfigUpdate {
	enabled?: boolean;
	device?: string;
	quality?: string;
}

export interface AuthConfigUpdate {
	single_user_allow_multiple_sessions?: boolean;
}

export interface Ch9329DescriptorConfigUpdate {
	vendor_id?: number;
	product_id?: number;
	manufacturer?: string;
	product?: string;
	serial_number?: string;
}

export interface Ch9329DescriptorState {
	descriptor: Ch9329DescriptorConfig;
	manufacturer_enabled: boolean;
	product_enabled: boolean;
	serial_enabled: boolean;
	config_mode_available: boolean;
}

export interface ComputerUseConfigResponse {
	enabled: boolean;
	base_url: string;
	model: string;
	api_key_configured: boolean;
	api_key_source: string;
}

export interface ComputerUseConfigUpdate {
	enabled?: boolean;
	base_url?: string;
	model?: string;
	api_key?: string;
	clear_api_key?: boolean;
}

export interface ComputerUsePoint {
	x: number;
	y: number;
}

export interface ComputerUseScreenshot {
	data_url: string;
	width: number;
	height: number;
}

export enum ComputerUseSessionStatus {
	Idle = "idle",
	WaitingScreenshot = "waiting_screenshot",
	Thinking = "thinking",
	Executing = "executing",
	Completed = "completed",
	Failed = "failed",
	Stopped = "stopped",
}

export interface ComputerUseSessionSummary {
	id?: string;
	status: ComputerUseSessionStatus;
	prompt?: string;
	step: number;
	last_error?: string;
	final_message?: string;
}

export interface ComputerUseStartRequest {
	prompt: string;
	continue_conversation?: boolean;
	client_id: string;
}

export interface EasytierConfigUpdate {
	enabled?: boolean;
	network_name?: string;
	network_secret?: string;
	peer_urls?: string[];
	virtual_ip?: string;
}

export type ExtensionStatus = 
	| { state: "unavailable", data?: undefined }
	| { state: "stopped", data?: undefined }
	| { state: "running", data: {
	pid: number;
}};

export interface EasytierInfo {
	available: boolean;
	status: ExtensionStatus;
	config: EasytierConfig;
}

export interface ExtensionInfo {
	available: boolean;
	status: ExtensionStatus;
}

export enum ExtensionId {
	Ttyd = "ttyd",
	Gostc = "gostc",
	Easytier = "easytier",
	Frpc = "frpc",
}

export interface ExtensionLogs {
	id: ExtensionId;
	logs: string[];
}

export interface TtydInfo {
	available: boolean;
	status: ExtensionStatus;
	config: TtydConfig;
}

export interface GostcInfo {
	available: boolean;
	status: ExtensionStatus;
	config: GostcConfig;
}

export interface FrpcInfo {
	available: boolean;
	status: ExtensionStatus;
	config: FrpcConfig;
}

export interface ExtensionsStatus {
	ttyd: TtydInfo;
	gostc: GostcInfo;
	easytier: EasytierInfo;
	frpc: FrpcInfo;
}

export interface FrpcConfigUpdate {
	enabled?: boolean;
	config_mode?: FrpcConfigMode;
	proxy_name?: string;
	proxy_type?: FrpProxyType;
	server_addr?: string;
	server_port?: number;
	token?: string;
	local_ip?: string;
	local_port?: number;
	remote_port?: number | null;
	custom_domain?: string | null;
	secret_key?: string;
	tls?: boolean;
	custom_toml?: string;
}

export interface GostcConfigUpdate {
	enabled?: boolean;
	addr?: string;
	key?: string;
	tls?: boolean;
}

/** OTG USB device descriptor configuration update */
export interface OtgDescriptorConfigUpdate {
	vendor_id?: number;
	product_id?: number;
	manufacturer?: string;
	product?: string;
	serial_number?: string;
}

export interface OtgHidFunctionsUpdate {
	keyboard?: boolean;
	mouse_relative?: boolean;
	mouse_absolute?: boolean;
	consumer?: boolean;
}

export interface HidConfigUpdate {
	backend?: HidBackend;
	ch9329_port?: string;
	ch9329_baudrate?: number;
	ch9329_hybrid_mouse?: boolean;
	ch9329_descriptor?: Ch9329DescriptorConfigUpdate;
	otg_udc?: string;
	otg_descriptor?: OtgDescriptorConfigUpdate;
	otg_profile?: OtgHidProfile;
	otg_functions?: OtgHidFunctionsUpdate;
	otg_keyboard_leds?: boolean;
	mouse_absolute?: boolean;
}

export interface MsdConfigUpdate {
	enabled?: boolean;
	msd_dir?: string;
}

export interface NetworkInterfaceInfo {
	name: string;
	interface_type: string;
	state: string;
	connection: string;
	addresses: string[];
	has_default_route: boolean;
	bridge_supported: boolean;
	reason?: string;
}

export enum OtgRuntimeHealth {
	Healthy = "healthy",
	Applying = "applying",
	Degraded = "degraded",
}

export interface OtgNetworkStatus {
	health: OtgRuntimeHealth;
	error?: string;
}

export interface OtgConfigResponse {
	hid: HidConfig;
	msd: MsdConfig;
	network: OtgNetworkConfig;
	status: OtgNetworkStatus;
}

export interface OtgNetworkConfigUpdate {
	enabled?: boolean;
	driver_mode?: OtgNetworkDriverMode;
	bridge_interface?: string;
	host_mac?: string;
	device_mac?: string;
}

export interface OtgConfigUpdate {
	hid?: HidConfigUpdate;
	msd?: MsdConfigUpdate;
	network?: OtgNetworkConfigUpdate;
}

export interface RtspConfigResponse {
	enabled: boolean;
	bind: string;
	port: number;
	path: string;
	allow_one_client: boolean;
	codec: RtspCodec;
	username?: string;
	password?: string;
}

export interface RtspConfigUpdate {
	enabled?: boolean;
	bind?: string;
	port?: number;
	path?: string;
	allow_one_client?: boolean;
	codec?: RtspCodec;
	username?: string;
	password?: string;
}

export interface RtspStatusResponse {
	config: RtspConfigResponse;
	service_status: string;
}

export interface RustDeskConfigUpdate {
	enabled?: boolean;
	codec?: RustDeskCodec;
	rendezvous_server?: string;
	relay_server?: string;
	relay_key?: string;
	device_password?: string;
}

/** Stream configuration response */
export interface StreamConfigResponse {
	mode: StreamMode;
	encoder: EncoderType;
	bitrate_preset: BitratePreset;
	/** Whether public ICE servers are available (compile-time decision) */
	has_public_ice_servers: boolean;
	/** Whether public ICE servers are currently in use (when STUN/TURN are unset) */
	using_public_ice_servers: boolean;
	stun_server?: string;
	turn_server?: string;
	turn_username?: string;
	turn_password?: string;
}

export interface StreamConfigUpdate {
	mode?: StreamMode;
	encoder?: EncoderType;
	bitrate_preset?: BitratePreset;
	/**
	 * STUN server URL (e.g., "stun:stun.l.google.com:19302")
	 * Leave empty to use public ICE servers
	 */
	stun_server?: string;
	/**
	 * TURN server URL (e.g., "turn:turn.example.com:3478")
	 * Leave empty to use public ICE servers
	 */
	turn_server?: string;
	/** TURN username */
	turn_username?: string;
	/** TURN password */
	turn_password?: string;
}

export interface TtydConfigUpdate {
	enabled?: boolean;
	shell?: string;
}

export interface VideoConfigUpdate {
	device?: string;
	format?: string;
	width?: number;
	height?: number;
	fps?: number;
	quality?: number;
}

export interface VncConfigResponse {
	enabled: boolean;
	bind: string;
	port: number;
	encoding: VncEncoding;
	allow_one_client: boolean;
	has_password: boolean;
}

export interface VncConfigUpdate {
	enabled?: boolean;
	bind?: string;
	port?: number;
	encoding?: VncEncoding;
	allow_one_client?: boolean;
	password?: string;
}

export interface VncStatusResponse {
	config: VncConfigResponse;
	service_status: string;
	connection_count: number;
}

export interface WatchdogConfigResponse {
	enabled: boolean;
	supported: boolean;
	running: boolean;
	reason?: string;
}

export interface WatchdogConfigUpdate {
	enabled: boolean;
}

/**
 * Web server settings returned by `GET` / `PATCH /api/config/web`.
 * 
 * Public API shape: certificate paths on disk are not exposed. The full stored model is `WebConfig` in `config::schema`.
 */
export interface WebConfigResponse {
	http_port: number;
	https_port: number;
	bind_addresses: string[];
	bind_address: string;
	https_enabled: boolean;
	/** Whether a custom TLS certificate is active (non-empty cert + key paths in stored config). */
	has_custom_cert: boolean;
}

export interface WebConfigUpdate {
	http_port?: number;
	https_port?: number;
	bind_addresses?: string[];
	bind_address?: string;
	https_enabled?: boolean;
	/** PEM-encoded certificate content (must be provided together with ssl_key_pem) */
	ssl_cert_pem?: string;
	/** PEM-encoded private key content (must be provided together with ssl_cert_pem) */
	ssl_key_pem?: string;
	/** Set to true to remove the custom certificate and revert to self-signed */
	clear_custom_cert?: boolean;
}

export enum CanonicalKey {
	KeyA = "KeyA",
	KeyB = "KeyB",
	KeyC = "KeyC",
	KeyD = "KeyD",
	KeyE = "KeyE",
	KeyF = "KeyF",
	KeyG = "KeyG",
	KeyH = "KeyH",
	KeyI = "KeyI",
	KeyJ = "KeyJ",
	KeyK = "KeyK",
	KeyL = "KeyL",
	KeyM = "KeyM",
	KeyN = "KeyN",
	KeyO = "KeyO",
	KeyP = "KeyP",
	KeyQ = "KeyQ",
	KeyR = "KeyR",
	KeyS = "KeyS",
	KeyT = "KeyT",
	KeyU = "KeyU",
	KeyV = "KeyV",
	KeyW = "KeyW",
	KeyX = "KeyX",
	KeyY = "KeyY",
	KeyZ = "KeyZ",
	Digit1 = "Digit1",
	Digit2 = "Digit2",
	Digit3 = "Digit3",
	Digit4 = "Digit4",
	Digit5 = "Digit5",
	Digit6 = "Digit6",
	Digit7 = "Digit7",
	Digit8 = "Digit8",
	Digit9 = "Digit9",
	Digit0 = "Digit0",
	Enter = "Enter",
	Escape = "Escape",
	Backspace = "Backspace",
	Tab = "Tab",
	Space = "Space",
	Minus = "Minus",
	Equal = "Equal",
	BracketLeft = "BracketLeft",
	BracketRight = "BracketRight",
	Backslash = "Backslash",
	Semicolon = "Semicolon",
	Quote = "Quote",
	Backquote = "Backquote",
	Comma = "Comma",
	Period = "Period",
	Slash = "Slash",
	CapsLock = "CapsLock",
	F1 = "F1",
	F2 = "F2",
	F3 = "F3",
	F4 = "F4",
	F5 = "F5",
	F6 = "F6",
	F7 = "F7",
	F8 = "F8",
	F9 = "F9",
	F10 = "F10",
	F11 = "F11",
	F12 = "F12",
	PrintScreen = "PrintScreen",
	ScrollLock = "ScrollLock",
	Pause = "Pause",
	Insert = "Insert",
	Home = "Home",
	PageUp = "PageUp",
	Delete = "Delete",
	End = "End",
	PageDown = "PageDown",
	ArrowRight = "ArrowRight",
	ArrowLeft = "ArrowLeft",
	ArrowDown = "ArrowDown",
	ArrowUp = "ArrowUp",
	NumLock = "NumLock",
	NumpadDivide = "NumpadDivide",
	NumpadMultiply = "NumpadMultiply",
	NumpadSubtract = "NumpadSubtract",
	NumpadAdd = "NumpadAdd",
	NumpadEnter = "NumpadEnter",
	Numpad1 = "Numpad1",
	Numpad2 = "Numpad2",
	Numpad3 = "Numpad3",
	Numpad4 = "Numpad4",
	Numpad5 = "Numpad5",
	Numpad6 = "Numpad6",
	Numpad7 = "Numpad7",
	Numpad8 = "Numpad8",
	Numpad9 = "Numpad9",
	Numpad0 = "Numpad0",
	NumpadDecimal = "NumpadDecimal",
	IntlBackslash = "IntlBackslash",
	ContextMenu = "ContextMenu",
	F13 = "F13",
	F14 = "F14",
	F15 = "F15",
	F16 = "F16",
	F17 = "F17",
	F18 = "F18",
	F19 = "F19",
	F20 = "F20",
	F21 = "F21",
	F22 = "F22",
	F23 = "F23",
	F24 = "F24",
	ControlLeft = "ControlLeft",
	ShiftLeft = "ShiftLeft",
	AltLeft = "AltLeft",
	MetaLeft = "MetaLeft",
	ControlRight = "ControlRight",
	ShiftRight = "ShiftRight",
	AltRight = "AltRight",
	MetaRight = "MetaRight",
}

export enum ComputerUseButton {
	Left = "left",
	Middle = "middle",
	Right = "right",
}
