#!/bin/bash
# ========================================================================== #
#                                                                            #
#    KVMD - The main PiKVM daemon.                                           #
#                                                                            #
#    Copyright (C) 2023-2025  SilentWind <mofeng654321@hotmail.com>         #
#                                                                            #
#    This program is free software: you can redistribute it and/or modify    #
#    it under the terms of the GNU General Public License as published by    #
#    the Free Software Foundation, either version 3 of the License, or       #
#    (at your option) any later version.                                     #
#                                                                            #
#    This program is distributed in the hope that it will be useful,         #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of          #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           #
#    GNU General Public License for more details.                            #
#                                                                            #
#    You should have received a copy of the GNU General Public License       #
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.  #
#                                                                            #
# ========================================================================== #
 
if [ -e /etc/update-motd.d/10-armbian-header ]; then /etc/update-motd.d/10-armbian-header; fi
if [ -e /etc/update-motd.d/30-armbian-sysinfo ]; then /etc/update-motd.d/30-armbian-sysinfo; fi
if [ -e /etc/update-motd.d/41-armbian-config ]; then /etc/update-motd.d/41-armbian-config; fi
 
printf "

 ██████╗ ███╗   ██╗███████╗    ██╗  ██╗██╗   ██╗███╗   ███╗
██╔═══██╗████╗  ██║██╔════╝    ██║ ██╔╝██║   ██║████╗ ████║
██║   ██║██╔██╗ ██║█████╗█████╗█████╔╝ ██║   ██║██╔████╔██║
██║   ██║██║╚██╗██║██╔══╝╚════╝██╔═██╗ ╚██╗ ██╔╝██║╚██╔╝██║
╚██████╔╝██║ ╚████║███████╗    ██║  ██╗ ╚████╔╝ ██║ ╚═╝ ██║
 ╚═════╝ ╚═╝  ╚═══╝╚══════╝    ╚═╝  ╚═╝  ╚═══╝  ╚═╝     ╚═╝

____________________________________________________________________________

项目链接：
    * One-KVM：https://github.com/mofeng-git/One-KVM

文档链接：
    * One-KVM：https://one-kvm.mofeng.run

____________________________________________________________________________

"