#!/bin/bash 
 
if [ -e /etc/update-motd.d/10-armbian-header ]; then /etc/update-motd.d/10-armbian-header; fi
if [ -e /etc/update-motd.d/30-armbian-sysinfo ]; then /etc/update-motd.d/30-armbian-sysinfo; fi
if [ -e /etc/update-motd.d/41-armbian-config ]; then /etc/update-motd.d/41-armbian-config; fi
 
printf "

 ██████╗ ███╗   ██╗███████╗    ██╗  ██╗██╗   ██╗███╗   ███╗
██╔═══██╗████╗  ██║██╔════╝    ██║ ██╔╝██║   ██║████╗ ████║
██║   ██║██╔██╗ ██║█████╗█████╗█████╔╝ ██║   ██║██╔████╔██║
██║   ██║██║╚██╗██║██╔══╝╚════╝██╔═██╗ ╚██╗ ██╔╝██║╚██╔╝██║
╚██████╔╝██║ ╚████║███████╗    ██║  ██╗ ╚████╔╝ ██║ ╚═╝ ██║
 ╚═════╝ ╚═╝  ╚═══╝╚══════╝    ╚═╝  ╚═╝  ╚═══╝  ╚═╝     ╚═╝

____________________________________________________________________________

欢迎使用 One-KVM，基于开源程序 PiKVM 的 IP-KVM 应用

项目链接：
    * One-KVM：https://github.com/mofeng-git/One-KVM

文档链接：
    * One-KVM：https://one-kvm.mofeng.run

____________________________________________________________________________

"