use std::fs;
use std::path::Path;

fn main() {
    // Set BUILD_DATE environment variable for compile-time access
    // Use system time to avoid adding chrono as a build dependency
    let now = std::time::SystemTime::now();
    let duration = now.duration_since(std::time::UNIX_EPOCH).unwrap();
    let secs = duration.as_secs();

    // Convert Unix timestamp to date (simplified calculation)
    // Days since epoch
    let days = secs / 86400;
    // Calculate year, month, day from days since 1970-01-01
    let (year, month, day) = days_to_ymd(days as i64);
    let build_date = format!("{:04}-{:02}-{:02}", year, month, day);

    println!("cargo:rustc-env=BUILD_DATE={}", build_date);

    // Compile protobuf files for RustDesk protocol
    compile_protos();

    // Generate minimal secrets module
    generate_secrets();

    // Rerun if the script itself changes
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=protos/rendezvous.proto");
    println!("cargo:rerun-if-changed=protos/message.proto");
}

/// Compile protobuf files using protobuf-codegen (same as RustDesk server)
fn compile_protos() {
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let protos_dir = out_dir.join("protos");
    std::fs::create_dir_all(&protos_dir).unwrap();

    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir(&protos_dir)
        .inputs(["protos/rendezvous.proto", "protos/message.proto"])
        .include("protos")
        .customize(protobuf_codegen::Customize::default().tokio_bytes(true))
        .run()
        .expect("Failed to compile protobuf files");

    // Generate mod.rs for the protos module
    let mod_content = r#"pub mod rendezvous;
pub mod message;
"#;
    std::fs::write(protos_dir.join("mod.rs"), mod_content).unwrap();
}

/// Generate minimal secrets module with Google STUN server hardcoded
fn generate_secrets() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("secrets_generated.rs");

    // Generate the secrets module - no public servers provided
    let code = r#"// Auto-generated secrets module
// DO NOT EDIT - This file is generated by build.rs

/// ICE server configuration (for WebRTC NAT traversal)
pub mod ice {
    /// Google public STUN server URL (hardcoded)
    pub const STUN_SERVER: &str = "stun:stun.l.google.com:19302";

    /// TURN server URLs - not provided, users must configure their own
    pub const TURN_URLS: &str = "";

    /// TURN authentication username
    pub const TURN_USERNAME: &str = "";

    /// TURN authentication password
    pub const TURN_PASSWORD: &str = "";

    /// Always returns true since we have STUN
    pub const fn is_configured() -> bool {
        true
    }

    /// Always returns false since TURN is not provided
    pub const fn has_turn() -> bool {
        false
    }
}

/// RustDesk public server configuration - NOT PROVIDED
pub mod rustdesk {
    /// Public RustDesk ID server - NOT PROVIDED
    pub const PUBLIC_SERVER: &str = "";

    /// Public key for the RustDesk server - NOT PROVIDED
    pub const PUBLIC_KEY: &str = "";

    /// Relay server authentication key - NOT PROVIDED
    pub const RELAY_KEY: &str = "";

    /// Always returns false
    pub const fn has_public_server() -> bool {
        false
    }
}
"#;

    fs::write(&dest_path, code).expect("Failed to write secrets_generated.rs");
}

/// Convert days since Unix epoch to year-month-day
fn days_to_ymd(days: i64) -> (i32, u32, u32) {
    // Algorithm from http://howardhinnant.github.io/date_algorithms.html
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = (z - era * 146097) as u32;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if m <= 2 { y + 1 } else { y };
    (year as i32, m, d)
}
