_MassStorageDeviceInfo.manufacturer
_MassStorageDeviceInfo.product
_MassStorageDeviceInfo.real
_MassStorageDeviceInfo.hw
_MassStorageDeviceInfo.image

IpmiServer.handle_raw_request

fake_rpi.RPi.GPIO

_KeyMapping.serial_hid_code
_KeyMapping.serial_hid_key
_KeyMapping.web_key

_ScriptWriter.get_args
